name: Compile C code

on:
  push:
    branches:
      - personal

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compile C
        working-directory: c_prgms
        run: make -j$(nproc)
