name: Compile code

on:
  push:
    branches:
      - my_stuff

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Building source files
        working-directory: c_prgms
        run: make -j$(nproc)
