name: Compile C code

on:
  push:
    branches:
      - sem_2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Building source files
        run: make -j$(nproc)
