name: Compile Python code

on:
  push:
    branches:
      - personal

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compile Python
        working-directory: python_prgms
        run: make -j$(nproc)

      - name: List compiled files
        working-directory: python_prgms
        run: ls -R src/__pycache__
