name: C/C++ CI

on:
  push:
    branches: 
      - "main"
      - "my_stuff"
  pull_request:
    branches: 
      - "main"
      - "my_stuff"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build source files
      run: make -j${nproc}
