name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install gcc
      run: sudo apt-get update && sudo apt-get install -y gcc make

    - name: Build school_stuff
      working-directory: c_programs/school_stuff
      run: make

    - name: Build my_stuff
      working-directory: my_stuff
      run: make
