name: Compile Python code

on:
  push:
    branches:
      - my_stuff

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.2'  # Specify the Python version you want

      - name: Install dependencies
        run: |
          # If you have dependencies to install, use pip
          # pip install -r requirements.txt
          echo "Skipping dependencies installation"

      - name: Compile Python files using Make
        working-directory: python_prgms
        run: make -j$(nproc)

      - name: List compiled files
        run: |
          ls -R src/__pycache__
